# Generated by Django 4.1.1 on 2022-09-10 20:12

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_sale_product_discount_product_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='UAH', max_digits=14, verbose_name='discount price'),
        ),
    ]
